name: CI

on:
  workflow_dispatch:
  schedule:
    # 详细cron设置请访问https://crontab.guru
    # 每天9点10分签到完所有账号，格式：'10 9 * * *'
    # 注意这里的时区是UTC，如果表示北京9点10分，UTC时间为1点10分，减8小时即可
    # 每天北京时间凌晨 1:00 触发
    - cron: "00 17 * * *"

jobs:
  infra:
    name: checkin
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/playwright-github-action@v1
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv sync
    - name: Install browsers
      run: pipenv run python -m playwright install
    - name: Run tests (Chromium and headless by default)
      env:
        USERNAME: ${{ secrets.TBJ_USERNAME }}
        PASSWD: ${{ secrets.TBJ_PASSWD }}
      run: pipenv run pytest
